In [21]:
import numpy as np
import tensorflow as tf

In [22]:
# declare placeholders

preds_tf = tf.placeholder(tf.float32, preds.shape)
targets_tf = tf.placeholder(tf.int32, targets.shape)

In [23]:
# construct graph

loss_op = tf.nn.sparse_softmax_cross_entropy_with_logits(labels=targets_tf, logits=preds_tf)

In [29]:
# generate feed values

preds = np.random.randn(2,2,2,4)
targets = np.digitize(np.random.randn(2,2,2), [-10, -1, 0, 1], right=True)

print(preds)
print(targets)

[[[[-0.15847    -0.07289354 -0.4907812   2.80184119]
   [ 0.70395841  0.55699133  2.42343123  0.48495053]]

  [[ 0.00854943  0.60075098 -0.31981773  0.34464993]
   [ 0.84885186  0.81269602 -1.38883846  1.30349374]]]


 [[[-0.2340621   0.50338463  0.98655519  1.12165306]
   [ 0.76261724 -0.59107254  1.26504965  1.64404055]]

  [[ 0.49196431  0.13576522 -0.60786669  0.77519007]
   [-0.16628439 -0.00358472 -1.8149417   2.14787572]]]]
[[[4 3]
  [2 3]]

 [[3 3]
  [4 3]]]


In [30]:
# run graph

with tf.Session() as sess:
    loss = sess.run(loss_op, feed_dict={preds_tf:preds, targets_tf:(targets-1)})

In [31]:
# examine output

print(loss.shape)
print(loss)

(2, 2, 2)
[[[ 0.13574532  0.39052498]
  [ 1.00263894  3.53154135]]

 [[ 1.1172775   1.17004704]
  [ 0.92891318  4.17321825]]]
